hyperparam:
  learning_rate: 1e-5  # adam: 1e-6
  batch_size: 4096
  step: 10000
  training_seed: 114514
  gradient_clipping: 1e-3  # adam: 1e-5
  log_epsilon: 1e-12

  mad_clipping_factor: 5
  scale_input: false

sampler:
  burn_in_steps: 100
  sample_steps: 10
  sampling_seed: 114514
  target_acceptance: 0.5
  init_width: 0.01
  sample_width: 0.02
  sample_width_adapt_freq: 100
  computation_dtype: "float32"

psiformer:
  num_of_determinants: 16
  num_of_blocks: 2
  num_heads: 4
  qkv_size: 64
  use_memory_efficient_attention: false
  group: null

  computation_dtype: "float32"
  param_dtype: "float32"

ckpt:
  save_ckpt: true
  ckpt_freq: 1000

  load_ckpt_dir: null
  load_config: true
  ckpt_step: null
